apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-rollouts
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-rollouts-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["configmaps", "events", "pods", "services", "endpoints"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["*"]
  - apiGroups: ["argoproj.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-rollouts-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: argo-rollouts
    namespace: default
roleRef:
  kind: Role
  name: argo-rollouts-role
  apiGroup: rbac.authorization.k8s.io

