apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: fastapi-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: ehdrjsxp/fastapi-app:c74bd6c9291340aa645a1ef33b5b468ee90d1676
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: mysql-secret
      imagePullSecrets:
      - name: regcred
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 10s}
      - setWeight: 50
      - pause: {duration: 10s}
      - setWeight: 100

