name: CI-CD to Azure Container Instances

on:
  push:
    branches:
      - main
    paths:
      - 'backend-rollout.yaml'
      - 'frontend-rollout.yaml'
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Backend 빌드 (Python)
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./fastapi_back

      - name: Run lint
        run: flake8 .
        working-directory: ./fastapi_back

      - name: Build backend Docker image
        run: docker build -t donggunacr.azurecr.io/fastapi-app:${IMAGE_TAG} ./fastapi_back

      # Frontend 빌드 (Node.js)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./react_front

      - name: Build frontend
        run: npm run build
        working-directory: ./react_front

      - name: Build frontend Docker image
        run: docker build -t donggunacr.azurecr.io/react-frontend:${IMAGE_TAG} ./react_front

      # Azure 로그인
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # ACR 로그인
      - name: Azure Container Registry Login
        uses: azure/docker-login@v1
        with:
          login-server: donggunacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # 이미지 푸시
      - name: Push backend image to ACR
        run: docker push donggunacr.azurecr.io/fastapi-app:${IMAGE_TAG}

      - name: Push frontend image to ACR
        run: docker push donggunacr.azurecr.io/react-frontend:${IMAGE_TAG}

      # ACI 배포
      - name: Deploy to Azure Container Instances (backend)
        uses: azure/aci-deploy@v1
        with:
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          dns-name-label: fastapi-backend-${{ github.run_id }}
          image: donggunacr.azurecr.io/fastapi-app:${IMAGE_TAG}
          name: fastapi-backend
          registry-login-server: donggunacr.azurecr.io
          registry-username: ${{ secrets.ACR_USERNAME }}
          registry-password: ${{ secrets.ACR_PASSWORD }}

      - name: Deploy to Azure Container Instances (frontend)
        uses: azure/aci-deploy@v1
        with:
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          dns-name-label: react-frontend-${{ github.run_id }}
          image: donggunacr.azurecr.io/react-frontend:${IMAGE_TAG}
          name: react-frontend
          registry-login-server: donggunacr.azurecr.io
          registry-username: ${{ secrets.ACR_USERNAME }}
          registry-password: ${{ secrets.ACR_PASSWORD }}
